[tools]
# Go Packages
"go:github.com/spf13/cobra-cli" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:github.com/vektra/mockery/v2" = "latest"
"go:github.com/google/go-licenses" = "latest"
"go:github.com/swaggo/swag/v2/cmd/swag" = "v2.0.0-rc5"


# API documentation tools
"npm:openapi-to-postmanv2" = "latest"     # Convert OpenAPI to Postman
"npm:@apidevtools/swagger-cli" = "latest" # Validate OpenAPI specs
"npm:newman" = "latest"                   # Postman CLI test runner

go = "1.25.7"
markdownlint-cli2 = "0.18.1"
yamlfmt = "0.20.0"
yamllint = "1.37.1"
yq = "4.48.1"
prettier = "3.7.4"
golines = "latest"
golangci-lint = "2.8.0"
actionlint = "latest"

# helm
helm = "3.19.0"
helm-cr = "latest"
helm-ct = "latest"
helm-diff = "latest"
helm-docs = "latest"
