apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: server-price-tracker
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: kube-system
  hostnames:
    - "tracker.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: server-price-tracker
          port: 8080
