apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: server-price-tracker

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - servicemonitor.yaml

labels:
  - pairs:
      app: server-price-tracker
    includeSelectors: true
