apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: server-price-tracker
spec:
  selector:
    matchLabels:
      app: server-price-tracker
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
