---
# yamlfmt configuration for Helm charts
formatter:
  type: basic
  indent: 2
  include_document_start: true
  line_ending: lf
  retain_line_breaks: true
  max_line_length: 150
  scan_folded_as_literal: false
  indentless_arrays: false
  drop_merge_tag: false
  pad_line_comments: 2
  trim_trailing_whitespace: true
  retain_line_breaks_single: true
