apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: server-price-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/donaldgifford/server-price-tracker.git
    targetRevision: main
    path: deploy/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: server-price-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
